name: Arch Linux
on: [push, pull_request]

env:
    GITHUB_REPO:    pmem/libpmemobj-cpp
    DOCKERHUB_REPO: ldorau/libpmemobj-cpp
    #
    OS:     archlinux-base
    OS_VER: latest

jobs:
  linux:
    name: Arch Linux
    runs-on: ubuntu-latest
    env:
      HOST_WORKDIR:   /home/runner/work/libpmemobj-cpp/libpmemobj-cpp
      WORKDIR:        utils/docker
    strategy:
      matrix:
        CONFIG: ["TYPE=debug",
                 "TYPE=release",
                 "TYPE=valgrind",
                 "TYPE=memcheck_drd"]
    steps:
       - name: Clone the git repo
         uses: actions/checkout@v1

       - name: Pull or rebuild the image
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./pull-or-rebuild-image.sh

       - name: Run the build
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./build.sh

       - name: Push the image
         run: cd $WORKDIR && source ./set-vars.sh && ${{ matrix.CONFIG }} /bin/bash -c "if [[ -f ${CI_FILE_PUSH_IMAGE_TO_REPO} ]]; then images/push-image.sh $OS-$OS_VER; fi"
